pelias/polylines

bin/cli.js
- exit(1) if stdin is a TTY
- add shebang
this will prevent the cli from hanging waiting for input from `stdin`.
cc/ @orangejulius
=> exit(1) if stdin is a TTY; add shebang

README.md
README referenced the old importer-specific method of enabling adminLookup
=> updated README for location of adminLookup setting

README.md
Option was removed a while ago so it shouldn't show up in the example https://github.com/pelias/config/pull/52
=> Remove old admin-lookup option

README.md
Calls attention to "polyline", not "polylines" in the imports of the config file
Fixes https://github.com/pelias/polylines/issues/73
=> Note the singular "polyline" in config file

Dockerfile, README.md
The [missinglink/pbf](https://github.com/missinglink/pbf) now requires Go 1.9+, so upgrade to 1.10, the current latest.
Without this, Docker images fail to build.
Connects https://github.com/missinglink/pbf/issues/13
=> Update to go 1.10

.travis.yml, README.md, package.json
This is a general documentation update with a few specific changes:
* all download URLs now point to the Nextzen S3 bucket, instead of the now deleted Mapzen S3 bucket
* Node.js 4 support is dropped, Node.js 8 support is added
* Mention of the deprecated Vagrant image is replaced with a link to the Dockerfiles setup
Connects https://github.com/pelias/pelias/issues/693
Connects https://github.com/pelias/pelias/issues/703
=> Update documentation and remove Node.js 4 support

docker_extract.sh
@orangejulius I've seen a few reports coming through about `missinglink/pbf` running out of memory when run on large extracts.
unfortunately, this is by design and it's intended that the Valhalla extract method is used for larger extract.
that's not very clear when using the docker setup because it bundles `missinglink/pbf` in with this code.
merging this will have two benefits:
- it will bring in the memory optimizations from https://github.com/missinglink/pbf/pull/15 which AFAIK haven't been released in a `latest` image for 
this repo yet (22 days vs. 18 days)
- it will spit out a very ugly warning message if the extract is over 1GB (we can change this constant), so that it will be in the logs just before any out-of-memory error is printed.
=> improved error checking, add warning for large PBF extracts

README.md
Links are broken, I got this error:
```xml
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Bucket>pelias-data.nextzen.org</Bucket>
<Endpoint>pelias-data.nextzen.org.s3.amazonaws.com</Endpoint>
<RequestId>796258F421A15491</RequestId>
<HostId>
xf9Gx7m1JXiRtBrUpYchrkEU7w+YmdirOkEhUwbCyYfBOo07wr4h8r0vMmuEMUcrzYbZTka2EPg=
</HostId>
</Error>
```
=> fix: polylines links

Dockerfile
This is now handled in the baseimage
=> Remove apt install of build-essential

bin/test, package.json
The way we were running our unit tests does not catch fatal errors in
the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail`
option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744
=> feat(test): Use dedicated test script to catch errors

Dockerfile, bin/start, package.json
By using a dedicated start script instead of `npm start` when running Docker images, we can avoid issues with passing signals through to the underlying processes.
This also avoids issues with `npm` requiring write permissions to the root filesystem.
This PR also changes the Dockerfile to ensure repeated local Docker builds are speed up by avoiding extra runs of `npm install` when not needed.
Connects https://github.com/pelias/pelias/issues/745
=> Support read-only root fs when running in Docker containers

docker_extract.sh
I just discovered https://github.com/pelias/polylines/issues/201 and Instead of just fixing that as-is I figured, why not support multiple PBF files?
I'm not sure why we decided to only extract the first OSM PBF file found in the directory.
This PR fixes 201, meaning that users who had multiple PBF files listed in their pelias.json would suffer a failed interpolation build and presumably street import too.
With this PR all the streets are imported into both ES and Interpolation.
resolves https://github.com/pelias/polylines/issues/201
=> docker_extract.sh support for multiple PBF files

docker_extract.sh
Using [ls for detecting files is problematic](https://mywiki.wooledge.org/ParsingLs), and in my case, running `pelias prepare polylines` did not detect my PBF file.
It turns out that using file globbing is quite simple for this, and works well.
=> fix(docker_extract): detect files without using ls

bin/cli.js, package.json
This allows distinguishing which logger output lines correspond to which importer during an import.
Connects https://github.com/pelias/dbclient/issues/101
=> feat(logger): Use dbclient name functionality

package.json
Usage of this package was removed in https://github.com/pelias/polylines/pull/209, but the package itself was missed.
Closes https://github.com/pelias/polylines/pull/211
=> feat(deps): Remove check-types package

README.md
There is code somewhere (I haven't figured out where yet) that is looking for the .0sv extension on the polylines file - so you have to use .0sv currently. 
```
jeremyr@bolt88:/data_c/users/jeremy/pelias/docker/projects/planet$ pelias prepare interpolation
ls: cannot access '/data/polylines/*.0sv': No such file or directory
- importing polylines
polyline line not found
```
This occurs when using the 'polylines' extension on the file, (and in pelias.json )
```
"imports": {
"polyline": {
"datapath": "/data/interpolation",
"files": [ "planet.polylines" ]
}
}
```
when I replace .polylines with .0sv then all is well
=> there is code somewhere looking for .0sv

README.md, bin/reencode.js
There was inadequate documentation for our use of polyline precision 6.
In many libraries the default precision value is 5, which is incompatible with our code.
see: https://www.mapzen.com/blog/polyline-precision/ for background info.
- add convenience script to re-encode polylines generated at precision 5 to precision 6
- add documentation to README
=> documentation related to polyline precision 6

stream/parser.js, test/stream/parser.js
We have had numerous reports from Pelias users about concerning error message during builds regarding the URL regex filter from https://github.com/pelias/model/pull/115.
While this filter is good, the resulting error message is alarming. Looking today at the output of a planet build, it appears that many of these errors come from the polylines file created by Valhalla out of the
OSM street network.
Looking at the contents of the polyline file and corresponding record on OSM, it seems that Valhalla puts the contents of the `ref` tag in the polyline file as an alternate name. The [ref tag](https://wiki.openstreetmap.org/wiki/Key:ref?uselang=en-US) will
often contain a URL.
This means that not only will the error happen frequently, but many records that are actaully valid will be filtered …
=> feat(parser): Filter out URLs before sending to pelias/model

package.json, stream/centroid.js, stream/parser.js, test/stream/centroid.js
Terf is now namespaced in the `@terf` package and sub-packages. Mapbox packages are also now namespaced under `@mapbox`.
=> Update deps to new namespaced versions

package.json, stream/pipeline.js
resolves https://github.com/pelias/polylines/issues/245
- update `wof-admin-lookup` to `6.5.1` which handles termination of workers when the input file is empty
- some minor code aesthetics to trigger a build: use split2 module, modernize require statements
When a polylines import references an empty file, it will now exit with the following log messages:
```bash
2020-03-18T09:43:01.423Z - info: [wof-admin-lookup] Shutting down admin lookup service
2020-03-18T09:43:01.423Z - info: [wof-admin-lookup] Ensure your input file is valid before retrying
```
=> empty polylines file

Dockerfile
upgrade Golang version and set `GO111MODULE=on`
closes https://github.com/pelias/polylines/issues/256
see: https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k
=> upgrade Golang version and set GO111MODULE=on

docker_extract.sh
By default, the algorithm to generate polyline data from a PBF file is the `pbf streets` command from my https://github.com/missinglink/pbf repo.
This algorithm is memory-bound and so doesn't scale well past a city or small country on modest hardware.
I made some attempts in the past to [spit out a very ugly warning message](https://github.com/pelias/polylines/pull/167), but this warning is easy to miss.
Recently https://github.com/pelias/polylines/issues/245 highlighted that even 125GB RAM is insufficient for the `pbf streets` command to process the whole planet.
As such **I'm going to turn this warning into a fatal error**.
The current upper limit for a PBF file is 1GB, which I'm open to changing if it's shown that the `pbf streets` is able to handle larger PBF files on modest hardware …
=> change missinglink/pbf warning to fatal error

Dockerfile
The polylines Docker image is a bit of a large one currently, as it includes not just Node.js and a `node_modules` directory, but a full compiler toolchain, an install of the Go language, the dependencies of the `pbf` repository from https://github.com/missinglink/pbf, and the final `pbf` executable that comes from it.
All told, this brought the total image size to a whopping 950MB uncompressed.
This PR makes use of multi stage builds to run the compiling of the `pbf` executable in a separate container. After this, all the toolchain and dependencies needed can be thrown away, and only the small executable copied to the final image.
Using `container-diff` it looks like the image size, uncompressed, after https://github.com/pelias/docker-baseimage/pull/23 as well, will be only 322MB. That's …
=> Use multistage build to bring in `pbf` executable

package.json
this PR upgrades `pelias/model` to the latest version.
looking through [the changelog](https://github.com/pelias/model/releases) there is nothing which will effect the Polylines importer, which is probably why we didn't do this sooner.
=> upgrade pelias-model to latest version

README.md
I replaced `go get` with `go install` as the execution of the first gave the following message:
'go get' is no longer supported outside a module. To build and install a command, use 'go install' with a version, like 'go install example.com/cmd@latest'.
=> docs: go install instead of go get

Dockerfile
this PR detects the target architecture and selects the correct Golang download accordingly.
> note: the `TARGETPLATFORM` is something like `linux/arm64` and the `${TARGETPLATFORM##*/}` command selects everything after the last slash.
=> dockerfile: correctly select Go architecture

stream/parser.js, test/stream/parser.js
This PR adjusts the URL detection regex by removing the leading `^` caret anchor.
This allows us to detect URLs *within* strings containing other characters.
Found via: https://github.com/pelias/polylines/issues/279#issuecomment-2527853636
Originally added in: https://github.com/pelias/polylines/commit/d4c530541d2adaf9bf91939c30aa69df483fd736
=> remove URL regex caret anchor
